class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror6'
        self.UnzipMirrorCommand = 'extract6'
        self.TarMirrorCommand = 'tar6'
        self.CancelMirror = 'cancel6'
        self.CancelAllCommand = 'cancelall6'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'auth6'
        self.UnAuthorizeCommand = 'unauth6'
        self.AuthListCommand = 'authlist6'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart6'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone'
        self.WatchCommand = 'ytdl'
        self.TarWatchCommand = 'playlist'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.RepoCommand = 'repo6'
        self.ConfigCommand = 'config'

BotCommands = _BotCommands()
